tests and program done
Vova4o/go-db-sql-final pull request #1
Opened 2024-02-09 13:52 UTC by Vova4o

Here is pull request, I didn't remove the comments cause I would like to keep it.
There is also a comment at the bottom of the test that I didn't understood how to do...

2024-02-10 07:25 UTC, robotomize requested changes
В целом все хорошо, но есть моменты, которые лучше поправить

2024-02-10 07:25 UTC, robotomize commented on parcel.go
> +	}
Нужно обработать еще rows.Err() после вашего цикла получения набора строк

2024-02-10 07:25 UTC, robotomize commented on parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET address = ? WHERE number = ?", address, number)
Вот тут есть условие которое нужно выполнить. Вариантов скорее всего 2

- вам нужно добавить проверку статуса в WHERE
- вам нужно получить объект проверить его статус с соответствующей константой, которая уже существует и выдать например ошибку

2024-02-10 07:25 UTC, robotomize commented on parcel_test.go
> +	if err != nil {
Функции для тестирования assert, require, работающие с ошибками не предполагают особо, что вы ошибку будете проверять
просто расположите эти require подряд

2024-02-10 07:25 UTC, robotomize commented on parcel_test.go
> +	assert.Equal(t, parcel.Address, storedParcel.Address)
Можно в целом сделать следующим образом, чтобы не писать много кода и пвоерять каждое поле отдельно после того, как добавили посылку в БД и проверили, что нет ошибки

```go
parcel.Number = id
assert.Equal(t, parcel, storedParcel)

```

2024-02-10 07:25 UTC, robotomize commented on parcel_test.go
> +		require.NoError(t, err)
Тут лучше не проверять на ошибке. Это инфраструктура, просто сделайте t.Fatal(err). Этого будет достаточно

2024-02-10 07:25 UTC, robotomize commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number], parcel)
Вам нужно просто сделать что-то подобное
```
p, ok := parcelMap[parcel.Number]
assert.True(t, ok)
assert.Equal(t, p, parcel)
```

2024-02-10 07:25 UTC, robotomize commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number], parcel)
Но в целом можно даже оставить ваще
assert.Equal(t, parcelMap[parcel.Number], parcel) по сути если в мапе ничего не будет объект будет сравниваться с пустым объектом и все равно будет не совпадать

2024-02-10 07:25 UTC, robotomize commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number].Address, parcel.Address)
Это в целом можно сократить, так как сверху мы объект с объектом сравнили

2024-02-10 07:25 UTC, robotomize commented on parcel_test.go
> +	if err != nil {
Про подобные блоки в самом верху написал

2024-02-10 07:48 UTC, Vova4o commented on parcel.go
> +	}
Саписибо, я этого не знал. Сейчас почитал по диагонали и понял что мы проверяем на правильность чтения из БД в переменные, ну или около того.
Добавил пару строк кода.

2024-02-10 07:59 UTC, Vova4o commented on parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET address = ? WHERE number = ?", address, number)
Пытался понять что тут от меня хотят, наконецто понял,
Дополнил метод и еще добавил проверку в предидущий метод SetStatus...
Главное чтобы это все не рухнуло...

2024-02-10 08:03 UTC, Vova4o commented on parcel_test.go
> +	if err != nil {
Я так понимаю вы про if err != nil{
Я тоже если честно подумал что жто бред, но так было показано в тесте Яндекса... 
![Screenshot 2024-02-10 110239](https://github.com/Vova4o/go-db-sql-final/assets/110772568/3dbaf075-14bc-4b8c-8134-6fb2cf7847fe)

2024-02-10 08:06 UTC, Vova4o commented on parcel_test.go
> +	assert.Equal(t, parcel.Address, storedParcel.Address)
Я помню почему я так сделал, у меня вылетала ошибка на этом тесте постоянно, так как ID у хочу 0 а ID у имею ХХ
Любое другое но не 0...
Попробую переделать.

2024-02-10 08:21 UTC, Vova4o commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number], parcel)
Я тут руководствовался тем, что мы проверяем одну посылку за раз так-как они в for loop.
А если одна посылка за раз то и сравникаем ее с одной посылкой из мапы главное чтобы номера совпадали...

2024-02-10 08:22 UTC, Vova4o commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number].Address, parcel.Address)
Видимо побоялся предидущего казуса с ID и просто сравнил все поля одно за другим...

2024-02-10 08:26 UTC, Vova4o commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number].Address, parcel.Address)
Посмотрел на код, и не совсем понимаю как укоротить данный запрос если требуется проверить что значения полей заполнены верно...

2024-02-10 14:42 UTC, robotomize commented on parcel_test.go
> +	assert.Equal(t, parcel.Address, storedParcel.Address)
Да, я там вот и написал что надо присвоить ему id который вы получили при создании

2024-02-10 14:43 UTC, robotomize commented on parcel_test.go
> +	if err != nil {
Кхм, ну ок,  можно и так

2024-02-10 14:45 UTC, robotomize commented on parcel_test.go
> +	if err != nil {
Просто можно сразу опуская if err туда пропихивать данные. Но в этом конкретном слчае с инициализацией db conn я бы вообще сделал t.Fatal(err), чтобы не путаться

2024-02-10 14:47 UTC, robotomize commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number].Address, parcel.Address)
```
p, ok := parcelMap[parcel.Number]
assert.True(t, ok)
assert.Equal(t, p, parcel)
```

2024-02-10 14:48 UTC, robotomize commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number].Address, parcel.Address)
Можете оставить проверку по полям, это вообще не ошибка, это просто оптимизация

2024-02-10 14:51 UTC, robotomize requested changes
Привет! К сожалению еще одна итерация, пофиксите Delete и используйте константы статусов, написал подробнее в самих ревью. После этого принимаем

2024-02-10 14:51 UTC, robotomize commented on parcel.go
> +		if currentStatus != "registered" {
registered, sent, delivered нужно не использовать на прямую. Используйте соответствуюшие константы, котоыре уже определны в коде, скорее всегов  main

2024-02-10 14:51 UTC, robotomize commented on parcel.go
> +	if currentStatus != "registered" {
Также про константы

2024-02-10 14:51 UTC, robotomize commented on parcel.go
> +	_, err := s.db.Exec("DELETE FROM parcel WHERE number = ?", number)
Забыли про то что удалять можно со статусом registered, не забудьте про константы

2024-02-10 23:05 UTC, Vova4o commented on parcel.go
> +		if currentStatus != "registered" {
Нашел константы, пофиксил. Ну да если мы потом в процессе захотим чтото поменять то меняем только в самой константе а не лезем вдоль всего кода...

2024-02-10 23:09 UTC, Vova4o commented on parcel_test.go
> +	if err != nil {
Так а как правильно? Я просто не понимаю зачем еще ошибку на ошибку проверять. Если это продакшен то понятно если ошибка не равна нулю идем дальше, но это то тестновый файл, а суть тестов вроде как и искать ошибки, Ну в общем мне показалось масло масляное...
Ах да еще не совсем понимаю разницу между requier and t.Fatal как я понял Fatal просто закроет тест и вылетит с криками все пропало...
Но requier вроде как делает тоже самое...

2024-02-11 02:35 UTC, robotomize commented on parcel_test.go
> +	if err != nil {
Разницы почти никакой, testify просто обертка над testing, так что в целом особой нет, результат одинаковый будет. Я бы скорее сделал или
```
if err != nil { t.Fatal(err)}
```
В кейсе с открытием соединения
или уже
```
require.NoError(t, err)
```
Без if

2024-02-11 02:39 UTC, robotomize approved these changes
Принято, оставил еще один коммент по поводу проверки конкретной ошибки

2024-02-11 02:39 UTC, robotomize commented on parcel_test.go
> +	require.Error(t, err)
Тут не совсем корректно. Лучше использовать require.ErrorIs(t, ) чтобы проверить на конкретную ошибку sql.ErrNoRows

2024-06-23 11:42 UTC, merged